
CREATE TABLE IF NOT EXISTS student (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  birth_date DATE NOT NULL,
  email VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS book (
    isbn INT AUTO_INCREMENT PRIMARY KEY,
    author VARCHAR(250) NOT NULL,
    student_id INT NOT NULL,
    FOREIGN KEY (student_id) REFERENCES student(id)
);

CREATE SEQUENCE BOOK_SEQ START WITH 1 INCREMENT BY 1;

